In [2]:
import tensorflow as tf

# Membuat tensor dengan shape(5,5) dengan nilai random

In [53]:
random_tensor = tf.random.uniform([5,5],maxval=10,dtype=tf.int64)
print(random_tensor)

tf.Tensor(
[[6 1 8 5 4]
 [3 4 1 8 9]
 [4 7 6 8 8]
 [8 3 9 9 8]
 [4 7 9 2 7]], shape=(5, 5), dtype=int64)


### Menampilkan Dimensi random_tensor

In [54]:
print(random_tensor.shape)

(5, 5)


# Membuat tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima

In [55]:
prime_tensor = tf.constant([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97], shape= (5,5), dtype=tf.int64 )
print(prime_tensor)

tf.Tensor(
[[ 2  3  5  7 11]
 [13 17 19 23 29]
 [31 37 41 43 47]
 [53 59 61 67 71]
 [73 79 83 89 97]], shape=(5, 5), dtype=int64)


### Menampilkan DImensi prime_tensor

In [56]:
print(prime_tensor.shape)

(5, 5)


# Aritmatika 2 variable


### Penjumlahan

In [57]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[  8   4  13  12  15]
 [ 16  21  20  31  38]
 [ 35  44  47  51  55]
 [ 61  62  70  76  79]
 [ 77  86  92  91 104]], shape=(5, 5), dtype=int64)


### Pengurangan


In [58]:
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[  4  -2   3  -2  -7]
 [-10 -13 -18 -15 -20]
 [-27 -30 -35 -35 -39]
 [-45 -56 -52 -58 -63]
 [-69 -72 -74 -87 -90]], shape=(5, 5), dtype=int64)


### Perkalian

In [59]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[ 12   3  40  35  44]
 [ 39  68  19 184 261]
 [124 259 246 344 376]
 [424 177 549 603 568]
 [292 553 747 178 679]], shape=(5, 5), dtype=int64)


### Pembagian

In [60]:
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[3.         0.33333333 1.6        0.71428571 0.36363636]
 [0.23076923 0.23529412 0.05263158 0.34782609 0.31034483]
 [0.12903226 0.18918919 0.14634146 0.18604651 0.17021277]
 [0.1509434  0.05084746 0.14754098 0.13432836 0.11267606]
 [0.05479452 0.08860759 0.10843373 0.02247191 0.07216495]], shape=(5, 5), dtype=float64)


### Perpangkatan

In [61]:
print(tf.pow(random_tensor, prime_tensor))

tf.Tensor(
[[                  36                    1                32768
                 78125              4194304]
 [             1594323          17179869184                    1
                     0  5756027422282277481]
 [ 4611686018427387904 -4589464050899304793 -4652000711771422720
                     0                    0]
 [                   0 -1178661806862719173  7528017780279371625
   4335951469400386777                    0]
 [                   0 -8070973709821280713  1885917819274684249
                     0 -3000843194277112057]], shape=(5, 5), dtype=int64)


# Menampilkan nilai maksimal dan minimal dari variable random_tensor

### Nilai Maks

In [62]:
max_sample_1 = tf.argmax(random_tensor, axis=0)
max_sample_2 = tf.argmax(random_tensor, axis=1)
print("Nilai Maksimum dari variable random_tensor berdasarkan kolom adalah : ", max_sample_1)
print("Nilai Maksimum dari variable random_tensor berdasarkan baris adalah : ", max_sample_2)

Nilai Maksimum dari variable random_tensor berdasarkan kolom adalah :  tf.Tensor([3 2 3 3 1], shape=(5,), dtype=int64)
Nilai Maksimum dari variable random_tensor berdasarkan baris adalah :  tf.Tensor([2 4 3 2 2], shape=(5,), dtype=int64)


### Nilai Minimum

In [63]:
min_sample_1 = tf.argmin(random_tensor, axis=0)
min_sample_2 = tf.argmin(random_tensor, axis=1)
print("Nilai Minimum dari variable random_tensor berdasarkan kolom adalah : ", min_sample_1)
print("Nilai Minimum dari variable random_tensor berdasarkan baris adalah : ", min_sample_2)

Nilai Minimum dari variable random_tensor berdasarkan kolom adalah :  tf.Tensor([1 0 1 4 0], shape=(5,), dtype=int64)
Nilai Minimum dari variable random_tensor berdasarkan baris adalah :  tf.Tensor([1 2 0 1 3], shape=(5,), dtype=int64)


# Concatenation

### Menggabungkan variable random_tensor dengan prime_tensor menggunakan metode tf.concat()

In [64]:
concat_sample = tf.concat([random_tensor,prime_tensor], axis = 0)
print(f"Size data yang sudah di-concat {concat_sample.shape}")
print(concat_sample)

Size data yang sudah di-concat (10, 5)
tf.Tensor(
[[ 6  1  8  5  4]
 [ 3  4  1  8  9]
 [ 4  7  6  8  8]
 [ 8  3  9  9  8]
 [ 4  7  9  2  7]
 [ 2  3  5  7 11]
 [13 17 19 23 29]
 [31 37 41 43 47]
 [53 59 61 67 71]
 [73 79 83 89 97]], shape=(10, 5), dtype=int64)


# Sorting kedua variable secara descending

### random_tensor

In [65]:
tf.sort(random_tensor, direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[8, 6, 5, 4, 1],
       [9, 8, 4, 3, 1],
       [8, 8, 7, 6, 4],
       [9, 9, 8, 8, 3],
       [9, 7, 7, 4, 2]], dtype=int64)>

### prime_tensor

In [66]:
tf.sort(prime_tensor, direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[11,  7,  5,  3,  2],
       [29, 23, 19, 17, 13],
       [47, 43, 41, 37, 31],
       [71, 67, 61, 59, 53],
       [97, 89, 83, 79, 73]], dtype=int64)>